### ISSUE TITLE
Word Document

### ISSUE THREAD

**Issue by akmalyezdani512** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#19]
Hi,
how do we convert these files to word.

**Comment by polichtm** [comment]
I updated README.md - pls refer to the instructions referenced at the beginning of that file and let us know if you have any additional questions
rgds
Marcin

**Comment by polichtm** [comment]
I gather this is resolved - pls let us know if you are still having issues with this
rgds
Marcin

**Comment by akmalyezdani512** [comment]
Still facing the Issue see below

"Akmal@DESKTOP-S7L70U5 MINGW64 ~
$ git remote add https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator.git
fatal: not a git repository (or any of the parent directories): .git

Akmal@DESKTOP-S7L70U5 MINGW64 ~
$ git remote add course https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator.git
fatal: not a git repository (or any of the parent directories): .git"

**Comment by polichtm** [comment]
Which instructions are you following?
rgds
Marcin
